name: CI

on:
  push:
    branches:
    - main
    paths:
    - '**.swift'
    - '**.yml'
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

jobs:
#  macOS:
#    runs-on: macOS-13
#    steps:
#    - name: Checkout
#      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
#    - name: SPM tests
#      run: swift test --enable-code-coverage
#    - name: Convert coverage files
#      run: |
#        xcrun llvm-cov export -format "lcov" \
#          .build/debug/hummingbirdPackageTests.xctest/Contents/MacOs/hummingbirdPackageTests \
#          -ignore-filename-regex="\/Tests\/" \
#          -ignore-filename-regex="\/Benchmarks\/" \
#          -instr-profile=.build/debug/codecov/default.profdata > info.lcov
#    - name: Upload to codecov.io
#      uses: codecov/codecov-action@v5
#      with:
#        file: info.lcov
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        image:
          - 'swift:6.1'
          - 'swift:6.2'
          - 'swift:6.3'
        postgres-image:
          - 'postgres:17'
          - 'postgres:16'
          - 'postgres:14'
        include:
          - postgres-image: postgres:17
            postgres-auth: scram-sha-256
          - postgres-image: postgres:16
            postgres-auth: scram-sha-256
          - postgres-image: postgres:14
            postgres-auth: md5
    container:
      image: ${{ matrix.image }}
      volumes: [ 'pgrunshare:/var/run/postgresql' ]
    env:
      POSTGRES_DB: 'test_database'
      POSTGRES_USER: 'test_user'
      POSTGRES_PASSWORD: 'test_password'
      POSTGRES_HOSTNAME: 'psql'
      POSTGRES_SOCKET: '/var/run/postgresql/.s.PGSQL.5432'
      POSTGRES_HOST_AUTH_METHOD: ${{ matrix.postgres-auth }}
    services:
      psql:
        image: ${{ matrix.postgres-image }}
        volumes: [ 'pgrunshare:/var/run/postgresql' ]
        env:
          POSTGRES_DB: 'test_database'
          POSTGRES_USER: 'test_user'
          POSTGRES_PASSWORD: 'test_password'
          POSTGRES_HOST_AUTH_METHOD: ${{ matrix.postgres-auth }}
          POSTGRES_INITDB_ARGS: --auth-host=${{ matrix.postgres-auth }}
    steps:
    - name: Install curl
      run: apt-get update -yq && apt-get install -y curl
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
    - name: Test
      run: |
        swift test --enable-code-coverage
    - name: Upload coverage data
      uses: vapor/swift-codecov-action@2f478f2fd22e06ca363967d0fb6c6593a8548cee  # v0.3.5
      with:
        codecov_token: ${{ secrets.CODECOV_TOKEN }}
